class ConfigHelper:
    SCEI_BASE_URL = "http://127.0.0.1:5004/happyface/v2/scei"
    EMOTIONISTANT_BASE_URL = "http://127.0.0.1:5003/happyface/v2/emotionistant"
    ORGANIZATION_EMOTION_ENDPOINT = f"{SCEI_BASE_URL}/emotions"
    SUBJECT_PROFILE_SUMMARIZE_ENDPOINT = f"{EMOTIONISTANT_BASE_URL}/summary"
    SUBJECT_PROFILES_TO_RECOMMENDATION = f"{EMOTIONISTANT_BASE_URL}/recommendation"
    SUBJECT_INIT_CONSULTANCY = f"{EMOTIONISTANT_BASE_URL}/init-consultancy"
    SUBJECT_QUERY_CONSULTANCY = f"{EMOTIONISTANT_BASE_URL}/query-consultancy"
    SUBJECT_SPECIAL_CONSIDERATION_INQUIRY = f"{SCEI_BASE_URL}/inquiry"
